/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author danismac
 */
public class VistaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form VistaCalculadora
     */
    public VistaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaResul = new javax.swing.JTextArea();
        clearBt = new javax.swing.JButton();
        sieteBt = new javax.swing.JButton();
        cuatroBt = new javax.swing.JButton();
        powBt = new javax.swing.JButton();
        ochoBt = new javax.swing.JButton();
        cincoBt = new javax.swing.JButton();
        divBt = new javax.swing.JButton();
        nueveBt = new javax.swing.JButton();
        seisBt = new javax.swing.JButton();
        unoBt = new javax.swing.JButton();
        dosBt = new javax.swing.JButton();
        tresBt = new javax.swing.JButton();
        sumaBt = new javax.swing.JButton();
        restaBt = new javax.swing.JButton();
        multipBt = new javax.swing.JButton();
        puntoBt = new javax.swing.JButton();
        parentesis1Bt = new javax.swing.JButton();
        parentesis2Bt = new javax.swing.JButton();
        ceroBt = new javax.swing.JButton();
        igualBt = new javax.swing.JButton();
        negBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JTextAreaResul.setBackground(new java.awt.Color(255, 237, 199));
        JTextAreaResul.setColumns(20);
        JTextAreaResul.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N
        JTextAreaResul.setRows(5);
        jScrollPane1.setViewportView(JTextAreaResul);

        clearBt.setBackground(new java.awt.Color(255, 196, 87));
        clearBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        clearBt.setText("AC");
        clearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtActionPerformed(evt);
            }
        });

        sieteBt.setBackground(new java.awt.Color(255, 196, 87));
        sieteBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        sieteBt.setText("7");
        sieteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBtActionPerformed(evt);
            }
        });

        cuatroBt.setBackground(new java.awt.Color(255, 196, 87));
        cuatroBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        cuatroBt.setText("4");
        cuatroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBtActionPerformed(evt);
            }
        });

        powBt.setBackground(new java.awt.Color(255, 196, 87));
        powBt.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        powBt.setText("pow");
        powBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powBtActionPerformed(evt);
            }
        });

        ochoBt.setBackground(new java.awt.Color(255, 196, 87));
        ochoBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        ochoBt.setText("8");
        ochoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBtActionPerformed(evt);
            }
        });

        cincoBt.setBackground(new java.awt.Color(255, 196, 87));
        cincoBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        cincoBt.setText("5");
        cincoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBtActionPerformed(evt);
            }
        });

        divBt.setBackground(new java.awt.Color(255, 196, 87));
        divBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        divBt.setText("/");
        divBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtActionPerformed(evt);
            }
        });

        nueveBt.setBackground(new java.awt.Color(255, 196, 87));
        nueveBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        nueveBt.setText("9");
        nueveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBtActionPerformed(evt);
            }
        });

        seisBt.setBackground(new java.awt.Color(255, 196, 87));
        seisBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        seisBt.setText("6");
        seisBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtActionPerformed(evt);
            }
        });

        unoBt.setBackground(new java.awt.Color(255, 196, 87));
        unoBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        unoBt.setText("1");
        unoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBtActionPerformed(evt);
            }
        });

        dosBt.setBackground(new java.awt.Color(255, 196, 87));
        dosBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        dosBt.setText("2");
        dosBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBtActionPerformed(evt);
            }
        });

        tresBt.setBackground(new java.awt.Color(255, 196, 87));
        tresBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        tresBt.setText("3");
        tresBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBtActionPerformed(evt);
            }
        });

        sumaBt.setBackground(new java.awt.Color(255, 196, 87));
        sumaBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        sumaBt.setText("+");
        sumaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBtActionPerformed(evt);
            }
        });

        restaBt.setBackground(new java.awt.Color(255, 196, 87));
        restaBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        restaBt.setText("-");
        restaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaBtActionPerformed(evt);
            }
        });

        multipBt.setBackground(new java.awt.Color(255, 196, 87));
        multipBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        multipBt.setText("x");
        multipBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipBtActionPerformed(evt);
            }
        });

        puntoBt.setBackground(new java.awt.Color(255, 196, 87));
        puntoBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        puntoBt.setText(".");
        puntoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBtActionPerformed(evt);
            }
        });

        parentesis1Bt.setBackground(new java.awt.Color(255, 196, 87));
        parentesis1Bt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        parentesis1Bt.setText("(");
        parentesis1Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis1BtActionPerformed(evt);
            }
        });

        parentesis2Bt.setBackground(new java.awt.Color(255, 196, 87));
        parentesis2Bt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        parentesis2Bt.setText(")");
        parentesis2Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis2BtActionPerformed(evt);
            }
        });

        ceroBt.setBackground(new java.awt.Color(255, 196, 87));
        ceroBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        ceroBt.setText("0");
        ceroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBtActionPerformed(evt);
            }
        });

        igualBt.setBackground(new java.awt.Color(255, 196, 87));
        igualBt.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        igualBt.setText("=");
        igualBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBtActionPerformed(evt);
            }
        });

        negBt.setBackground(new java.awt.Color(255, 196, 87));
        negBt.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        negBt.setText("neg");
        negBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(powBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sumaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(parentesis1Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(parentesis2Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(negBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sieteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ochoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nueveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(restaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuatroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cincoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(multipBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(puntoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ceroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(igualBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powBt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesis2Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentesis1Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igualBt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtActionPerformed

    private void sieteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sieteBtActionPerformed

    private void cuatroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuatroBtActionPerformed

    private void powBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powBtActionPerformed

    private void ochoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ochoBtActionPerformed

    private void cincoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoBtActionPerformed

    private void divBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divBtActionPerformed

    private void nueveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nueveBtActionPerformed

    private void seisBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisBtActionPerformed

    private void unoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unoBtActionPerformed

    private void dosBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosBtActionPerformed

    private void tresBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresBtActionPerformed

    private void sumaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaBtActionPerformed

    private void restaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaBtActionPerformed

    private void multipBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipBtActionPerformed

    private void puntoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntoBtActionPerformed

    private void parentesis1BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis1BtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentesis1BtActionPerformed

    private void parentesis2BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis2BtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentesis2BtActionPerformed

    private void ceroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceroBtActionPerformed

    private void igualBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_igualBtActionPerformed

    private void negBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextAreaResul;
    private javax.swing.JButton ceroBt;
    private javax.swing.JButton cincoBt;
    private javax.swing.JButton clearBt;
    private javax.swing.JButton cuatroBt;
    private javax.swing.JButton divBt;
    private javax.swing.JButton dosBt;
    private javax.swing.JButton igualBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton multipBt;
    private javax.swing.JButton negBt;
    private javax.swing.JButton nueveBt;
    private javax.swing.JButton ochoBt;
    private javax.swing.JButton parentesis1Bt;
    private javax.swing.JButton parentesis2Bt;
    private javax.swing.JButton powBt;
    private javax.swing.JButton puntoBt;
    private javax.swing.JButton restaBt;
    private javax.swing.JButton seisBt;
    private javax.swing.JButton sieteBt;
    private javax.swing.JButton sumaBt;
    private javax.swing.JButton tresBt;
    private javax.swing.JButton unoBt;
    // End of variables declaration//GEN-END:variables
}
